### ISSUE TITLE
Morning Session Peer to peer code review Module 2 Week 2

### ISSUE THREAD

**Issue by Diegogagan2587** [ClaudiaRojasSoto/Awesome_Books_ES6#2]
# Peer-to-peer code review
 implemented by  @demesameneshoa  @MohamedRoshdy2021 and @Diegogagan2587 to @ClaudiaRojasSoto 
 
 Great Job So far! your code is adding and removing the books correctly! Thanks for sharing! We were able to make some **optional** suggestions that you will see below:

**Comment by Diegogagan2587** [comment]
## Suggested Changes:

- Great work so far would be great if you add a function to prevent the user from saving empty data, this will avoid any error with the application
- Timing is looking great, we suggest improving user experience to add a function to get the time updated, you could set an interval of time every second and have it updated on the screen.
- Add bookmarks or comments in the Javascript to help understand better the code in case of review in the future.

**Comment by ClaudiaRojasSoto** [comment]
Thank you, guys. I'm working on that!!!

**Comment by ClaudiaRojasSoto** [comment]
The suggestion was implemented.
